[general]
push_to_talk = false
ptt_key = "Delete"
audio_client = "Jack"

[audio.jack]
input_port = "Noise Canceling source:capture_MONO"
output_ports = [
    "PCM2902 Audio Codec Analog Stereo:playback_FL",
    "PCM2902 Audio Codec Analog Stereo:playback_FR",
]

[whisper]
model="large-v2"
language = "de"
translate = true
no_context = false
silence_length = 10

[piper]
model = "en_US-lessac-high"
